
CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE, email TEXT, password TEXT, role_id INTEGER REFERENCES roles(id));
CREATE TABLE IF NOT EXISTS tariffs (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, description TEXT, price REAL);
CREATE TABLE IF NOT EXISTS contacts (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, email TEXT, message TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, fio TEXT, program TEXT, contract_number TEXT, amount REAL, currency TEXT DEFAULT 'rub', status TEXT DEFAULT 'pending', stripe_session_id TEXT, receipt_pdf TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
